/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    DataAgentFactory: {
      address: "0x9d4454B023096f34B160D6B654540c56A1F81688",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "oracleAddress",
              type: "address",
            },
          ],
          name: "createDataAgent",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
    LeadAgent: {
      address: "0x5eb3Bc0a489C5A8288765d2336659EbCA68FCd00",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "initialOracleAddress",
              type: "address",
            },
            {
              internalType: "string",
              name: "systemPrompt",
              type: "string",
            },
            {
              internalType: "address",
              name: "techAgentFactoryAddress",
              type: "address",
            },
            {
              internalType: "address",
              name: "socialAgentFactoryAddress",
              type: "address",
            },
            {
              internalType: "address",
              name: "dataAgentFactoryAddress",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "owner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "runId",
              type: "uint256",
            },
          ],
          name: "AgentRunCreated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "newOracleAddress",
              type: "address",
            },
          ],
          name: "OracleAddressUpdated",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "message",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "runId",
              type: "uint256",
            },
          ],
          name: "addMessage",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "agentRunCount",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "agentRuns",
          outputs: [
            {
              internalType: "address",
              name: "owner",
              type: "address",
            },
            {
              internalType: "address",
              name: "creator",
              type: "address",
            },
            {
              internalType: "address",
              name: "target",
              type: "address",
            },
            {
              internalType: "string",
              name: "targetFirstName",
              type: "string",
            },
            {
              internalType: "string",
              name: "targetFriend",
              type: "string",
            },
            {
              internalType: "string",
              name: "situation",
              type: "string",
            },
            {
              internalType: "string",
              name: "publicInfo",
              type: "string",
            },
            {
              internalType: "string",
              name: "privateInfo",
              type: "string",
            },
            {
              internalType: "string",
              name: "groupTitle",
              type: "string",
            },
            {
              internalType: "string",
              name: "groupImage",
              type: "string",
            },
            {
              internalType: "string",
              name: "groupId",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "responsesCount",
              type: "uint256",
            },
            {
              internalType: "uint8",
              name: "max_iterations",
              type: "uint8",
            },
            {
              internalType: "bool",
              name: "is_finished",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "dataAgent",
          outputs: [
            {
              internalType: "contract IOpenAiChatGpt",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_creator",
              type: "address",
            },
          ],
          name: "getAgentRuns",
          outputs: [
            {
              components: [
                {
                  internalType: "address",
                  name: "owner",
                  type: "address",
                },
                {
                  internalType: "address",
                  name: "creator",
                  type: "address",
                },
                {
                  internalType: "address",
                  name: "target",
                  type: "address",
                },
                {
                  internalType: "string",
                  name: "targetFirstName",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "targetFriend",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "situation",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "publicInfo",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "privateInfo",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "groupTitle",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "groupImage",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "groupId",
                  type: "string",
                },
                {
                  internalType: "uint256",
                  name: "responsesCount",
                  type: "uint256",
                },
                {
                  internalType: "uint8",
                  name: "max_iterations",
                  type: "uint8",
                },
                {
                  internalType: "bool",
                  name: "is_finished",
                  type: "bool",
                },
              ],
              internalType: "struct LeadAgent.AgentRunInfo[]",
              name: "",
              type: "tuple[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "agentId",
              type: "uint256",
            },
          ],
          name: "getMessageHistoryContents",
          outputs: [
            {
              internalType: "string[]",
              name: "",
              type: "string[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "agentId",
              type: "uint256",
            },
          ],
          name: "getMessageHistoryRoles",
          outputs: [
            {
              internalType: "string[]",
              name: "",
              type: "string[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "runId",
              type: "uint256",
            },
          ],
          name: "isRunFinished",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "runId",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "response",
              type: "string",
            },
            {
              internalType: "string",
              name: "errorMessage",
              type: "string",
            },
          ],
          name: "onOracleFunctionResponse",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "runId",
              type: "uint256",
            },
            {
              components: [
                {
                  internalType: "string",
                  name: "id",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "content",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "functionName",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "functionArguments",
                  type: "string",
                },
                {
                  internalType: "uint64",
                  name: "created",
                  type: "uint64",
                },
                {
                  internalType: "string",
                  name: "model",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "systemFingerprint",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "object",
                  type: "string",
                },
                {
                  internalType: "uint32",
                  name: "completionTokens",
                  type: "uint32",
                },
                {
                  internalType: "uint32",
                  name: "promptTokens",
                  type: "uint32",
                },
                {
                  internalType: "uint32",
                  name: "totalTokens",
                  type: "uint32",
                },
              ],
              internalType: "struct IOracle.OpenAiResponse",
              name: "response",
              type: "tuple",
            },
            {
              internalType: "string",
              name: "errorMessage",
              type: "string",
            },
          ],
          name: "onOracleOpenAiLlmResponse",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "oracleAddress",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "prompt",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "query",
              type: "string",
            },
            {
              internalType: "uint8",
              name: "max_iterations",
              type: "uint8",
            },
            {
              internalType: "string",
              name: "techAgentPrompt",
              type: "string",
            },
            {
              internalType: "string",
              name: "socialAgentPrompt",
              type: "string",
            },
            {
              internalType: "string",
              name: "dataAgentPrompt",
              type: "string",
            },
            {
              internalType: "address",
              name: "creator",
              type: "address",
            },
            {
              internalType: "address",
              name: "target",
              type: "address",
            },
            {
              internalType: "string",
              name: "targetFirstName",
              type: "string",
            },
            {
              internalType: "string",
              name: "targetFriend",
              type: "string",
            },
            {
              internalType: "string",
              name: "situation",
              type: "string",
            },
            {
              internalType: "string",
              name: "publicInfo",
              type: "string",
            },
            {
              internalType: "string",
              name: "privateInfo",
              type: "string",
            },
            {
              internalType: "string",
              name: "groupTitle",
              type: "string",
            },
            {
              internalType: "string",
              name: "groupImage",
              type: "string",
            },
            {
              internalType: "string",
              name: "groupId",
              type: "string",
            },
          ],
          name: "runAgent",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "newOracleAddress",
              type: "address",
            },
          ],
          name: "setOracleAddress",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "socialAgent",
          outputs: [
            {
              internalType: "contract IOpenAiChatGpt",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "techAgent",
          outputs: [
            {
              internalType: "contract IOpenAiChatGpt",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
    PrevOpenAiChatGpt: {
      address: "0x36C02dA8a0983159322a80FFE9F24b1acfF8B570",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "initialOracleAddress",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "owner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "chatId",
              type: "uint256",
            },
          ],
          name: "ChatCreated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "newOracleAddress",
              type: "address",
            },
          ],
          name: "OracleAddressUpdated",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "message",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "runId",
              type: "uint256",
            },
          ],
          name: "addMessage",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "chatRuns",
          outputs: [
            {
              internalType: "address",
              name: "owner",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "messagesCount",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "chatId",
              type: "uint256",
            },
          ],
          name: "getMessageHistoryContents",
          outputs: [
            {
              internalType: "string[]",
              name: "",
              type: "string[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "chatId",
              type: "uint256",
            },
          ],
          name: "getMessageHistoryRoles",
          outputs: [
            {
              internalType: "string[]",
              name: "",
              type: "string[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "runId",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "response",
              type: "string",
            },
            {
              internalType: "string",
              name: "errorMessage",
              type: "string",
            },
          ],
          name: "onOracleFunctionResponse",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "runId",
              type: "uint256",
            },
            {
              components: [
                {
                  internalType: "string",
                  name: "id",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "content",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "functionName",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "functionArguments",
                  type: "string",
                },
                {
                  internalType: "uint64",
                  name: "created",
                  type: "uint64",
                },
                {
                  internalType: "string",
                  name: "model",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "systemFingerprint",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "object",
                  type: "string",
                },
                {
                  internalType: "uint32",
                  name: "completionTokens",
                  type: "uint32",
                },
                {
                  internalType: "uint32",
                  name: "promptTokens",
                  type: "uint32",
                },
                {
                  internalType: "uint32",
                  name: "totalTokens",
                  type: "uint32",
                },
              ],
              internalType: "struct IOracle.OpenAiResponse",
              name: "response",
              type: "tuple",
            },
            {
              internalType: "string",
              name: "errorMessage",
              type: "string",
            },
          ],
          name: "onOracleOpenAiLlmResponse",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "oracleAddress",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "newOracleAddress",
              type: "address",
            },
          ],
          name: "setOracleAddress",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "message",
              type: "string",
            },
          ],
          name: "startChat",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
    SocialAgentFactory: {
      address: "0x8f86403A4DE0BB5791fa46B8e795C547942fE4Cf",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "oracleAddress",
              type: "address",
            },
          ],
          name: "createSocialAgent",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
    TechAgentFactory: {
      address: "0x0E801D84Fa97b50751Dbf25036d067dCf18858bF",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "oracleAddress",
              type: "address",
            },
          ],
          name: "createTechAgent",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
    TodoList: {
      address: "0x99bbA657f2BbC93c02D617f8bA121cB8Fc104Acf",
      abi: [
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "user",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
          ],
          name: "TodoCompleted",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "user",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "string",
              name: "content",
              type: "string",
            },
          ],
          name: "TodoCreated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "user",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
          ],
          name: "TodoDeleted",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_id",
              type: "uint256",
            },
          ],
          name: "completeTodo",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "_content",
              type: "string",
            },
          ],
          name: "createTodo",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_id",
              type: "uint256",
            },
          ],
          name: "deleteTodo",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "getTodos",
          outputs: [
            {
              components: [
                {
                  internalType: "uint256",
                  name: "id",
                  type: "uint256",
                },
                {
                  internalType: "string",
                  name: "content",
                  type: "string",
                },
                {
                  internalType: "bool",
                  name: "isCompleted",
                  type: "bool",
                },
                {
                  internalType: "uint256",
                  name: "createdAt",
                  type: "uint256",
                },
                {
                  internalType: "address",
                  name: "user",
                  type: "address",
                },
              ],
              internalType: "struct TodoList.Todo[]",
              name: "",
              type: "tuple[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
    YourContract: {
      address: "0x4826533B4897376654Bb4d4AD88B7faFD0C98528",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "_owner",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "greetingSetter",
              type: "address",
            },
            {
              indexed: false,
              internalType: "string",
              name: "newGreeting",
              type: "string",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "premium",
              type: "bool",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
          ],
          name: "GreetingChange",
          type: "event",
        },
        {
          inputs: [],
          name: "greeting",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "premium",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "_newGreeting",
              type: "string",
            },
          ],
          name: "setGreeting",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [],
          name: "totalCounter",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "userGreetingCounter",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "withdraw",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          stateMutability: "payable",
          type: "receive",
        },
      ],
      inheritedFunctions: {},
    },
  },
  696969: {
    DataAgentFactory: {
      address: "0xE92B718dDB54aB6613e0dA0511fD3D756A0E3c2d",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "oracleAddress",
              type: "address",
            },
          ],
          name: "createDataAgent",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
    LeadAgent: {
      address: "0x72645ff40fBB78f369789973F38f0686f407B3FA",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "initialOracleAddress",
              type: "address",
            },
            {
              internalType: "string",
              name: "systemPrompt",
              type: "string",
            },
            {
              internalType: "address",
              name: "techAgentFactoryAddress",
              type: "address",
            },
            {
              internalType: "address",
              name: "socialAgentFactoryAddress",
              type: "address",
            },
            {
              internalType: "address",
              name: "dataAgentFactoryAddress",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "owner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "runId",
              type: "uint256",
            },
          ],
          name: "AgentRunCreated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "newOracleAddress",
              type: "address",
            },
          ],
          name: "OracleAddressUpdated",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "message",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "runId",
              type: "uint256",
            },
          ],
          name: "addMessage",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "agentRunCount",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "agentRuns",
          outputs: [
            {
              internalType: "address",
              name: "owner",
              type: "address",
            },
            {
              internalType: "address",
              name: "creator",
              type: "address",
            },
            {
              internalType: "address",
              name: "target",
              type: "address",
            },
            {
              internalType: "string",
              name: "targetFirstName",
              type: "string",
            },
            {
              internalType: "string",
              name: "targetFriend",
              type: "string",
            },
            {
              internalType: "string",
              name: "situation",
              type: "string",
            },
            {
              internalType: "string",
              name: "publicInfo",
              type: "string",
            },
            {
              internalType: "string",
              name: "privateInfo",
              type: "string",
            },
            {
              internalType: "string",
              name: "groupTitle",
              type: "string",
            },
            {
              internalType: "string",
              name: "groupImage",
              type: "string",
            },
            {
              internalType: "string",
              name: "groupId",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "responsesCount",
              type: "uint256",
            },
            {
              internalType: "uint8",
              name: "max_iterations",
              type: "uint8",
            },
            {
              internalType: "bool",
              name: "is_finished",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "dataAgent",
          outputs: [
            {
              internalType: "contract IOpenAiChatGpt",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_creator",
              type: "address",
            },
          ],
          name: "getAgentRuns",
          outputs: [
            {
              components: [
                {
                  internalType: "address",
                  name: "owner",
                  type: "address",
                },
                {
                  internalType: "address",
                  name: "creator",
                  type: "address",
                },
                {
                  internalType: "address",
                  name: "target",
                  type: "address",
                },
                {
                  internalType: "string",
                  name: "targetFirstName",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "targetFriend",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "situation",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "publicInfo",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "privateInfo",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "groupTitle",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "groupImage",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "groupId",
                  type: "string",
                },
                {
                  internalType: "uint256",
                  name: "responsesCount",
                  type: "uint256",
                },
                {
                  internalType: "uint8",
                  name: "max_iterations",
                  type: "uint8",
                },
                {
                  internalType: "bool",
                  name: "is_finished",
                  type: "bool",
                },
              ],
              internalType: "struct LeadAgent.AgentRunInfo[]",
              name: "",
              type: "tuple[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "agentId",
              type: "uint256",
            },
          ],
          name: "getMessageHistoryContents",
          outputs: [
            {
              internalType: "string[]",
              name: "",
              type: "string[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "agentId",
              type: "uint256",
            },
          ],
          name: "getMessageHistoryRoles",
          outputs: [
            {
              internalType: "string[]",
              name: "",
              type: "string[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "runId",
              type: "uint256",
            },
          ],
          name: "isRunFinished",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "runId",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "response",
              type: "string",
            },
            {
              internalType: "string",
              name: "errorMessage",
              type: "string",
            },
          ],
          name: "onOracleFunctionResponse",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "runId",
              type: "uint256",
            },
            {
              components: [
                {
                  internalType: "string",
                  name: "id",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "content",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "functionName",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "functionArguments",
                  type: "string",
                },
                {
                  internalType: "uint64",
                  name: "created",
                  type: "uint64",
                },
                {
                  internalType: "string",
                  name: "model",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "systemFingerprint",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "object",
                  type: "string",
                },
                {
                  internalType: "uint32",
                  name: "completionTokens",
                  type: "uint32",
                },
                {
                  internalType: "uint32",
                  name: "promptTokens",
                  type: "uint32",
                },
                {
                  internalType: "uint32",
                  name: "totalTokens",
                  type: "uint32",
                },
              ],
              internalType: "struct IOracle.OpenAiResponse",
              name: "response",
              type: "tuple",
            },
            {
              internalType: "string",
              name: "errorMessage",
              type: "string",
            },
          ],
          name: "onOracleOpenAiLlmResponse",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "oracleAddress",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "prompt",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "query",
              type: "string",
            },
            {
              internalType: "uint8",
              name: "max_iterations",
              type: "uint8",
            },
            {
              internalType: "string",
              name: "techAgentPrompt",
              type: "string",
            },
            {
              internalType: "string",
              name: "socialAgentPrompt",
              type: "string",
            },
            {
              internalType: "string",
              name: "dataAgentPrompt",
              type: "string",
            },
            {
              internalType: "address",
              name: "creator",
              type: "address",
            },
            {
              internalType: "address",
              name: "target",
              type: "address",
            },
            {
              internalType: "string",
              name: "targetFirstName",
              type: "string",
            },
            {
              internalType: "string",
              name: "targetFriend",
              type: "string",
            },
            {
              internalType: "string",
              name: "situation",
              type: "string",
            },
            {
              internalType: "string",
              name: "publicInfo",
              type: "string",
            },
            {
              internalType: "string",
              name: "privateInfo",
              type: "string",
            },
            {
              internalType: "string",
              name: "groupTitle",
              type: "string",
            },
            {
              internalType: "string",
              name: "groupImage",
              type: "string",
            },
            {
              internalType: "string",
              name: "groupId",
              type: "string",
            },
          ],
          name: "runAgent",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "newOracleAddress",
              type: "address",
            },
          ],
          name: "setOracleAddress",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "socialAgent",
          outputs: [
            {
              internalType: "contract IOpenAiChatGpt",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "techAgent",
          outputs: [
            {
              internalType: "contract IOpenAiChatGpt",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
    PrevOpenAiChatGpt: {
      address: "0x193d8645aAa7F499351e9Efe066BfdAa72EAa636",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "initialOracleAddress",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "owner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "chatId",
              type: "uint256",
            },
          ],
          name: "ChatCreated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "newOracleAddress",
              type: "address",
            },
          ],
          name: "OracleAddressUpdated",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "message",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "runId",
              type: "uint256",
            },
          ],
          name: "addMessage",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "chatRuns",
          outputs: [
            {
              internalType: "address",
              name: "owner",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "messagesCount",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "chatId",
              type: "uint256",
            },
          ],
          name: "getMessageHistoryContents",
          outputs: [
            {
              internalType: "string[]",
              name: "",
              type: "string[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "chatId",
              type: "uint256",
            },
          ],
          name: "getMessageHistoryRoles",
          outputs: [
            {
              internalType: "string[]",
              name: "",
              type: "string[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "runId",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "response",
              type: "string",
            },
            {
              internalType: "string",
              name: "errorMessage",
              type: "string",
            },
          ],
          name: "onOracleFunctionResponse",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "runId",
              type: "uint256",
            },
            {
              components: [
                {
                  internalType: "string",
                  name: "id",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "content",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "functionName",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "functionArguments",
                  type: "string",
                },
                {
                  internalType: "uint64",
                  name: "created",
                  type: "uint64",
                },
                {
                  internalType: "string",
                  name: "model",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "systemFingerprint",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "object",
                  type: "string",
                },
                {
                  internalType: "uint32",
                  name: "completionTokens",
                  type: "uint32",
                },
                {
                  internalType: "uint32",
                  name: "promptTokens",
                  type: "uint32",
                },
                {
                  internalType: "uint32",
                  name: "totalTokens",
                  type: "uint32",
                },
              ],
              internalType: "struct IOracle.OpenAiResponse",
              name: "response",
              type: "tuple",
            },
            {
              internalType: "string",
              name: "errorMessage",
              type: "string",
            },
          ],
          name: "onOracleOpenAiLlmResponse",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "oracleAddress",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "newOracleAddress",
              type: "address",
            },
          ],
          name: "setOracleAddress",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "message",
              type: "string",
            },
          ],
          name: "startChat",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
    SocialAgentFactory: {
      address: "0xaF7B6E3DCdE8BaD4643b88d6dCd953A72edD6e30",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "oracleAddress",
              type: "address",
            },
          ],
          name: "createSocialAgent",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
    TechAgentFactory: {
      address: "0xD438b4245Bff99d112f637c155011F8066C9Efa9",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "oracleAddress",
              type: "address",
            },
          ],
          name: "createTechAgent",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
    TodoList: {
      address: "0x19005D86A17e701815Def4242d779d5A637e64A5",
      abi: [
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "user",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
          ],
          name: "TodoCompleted",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "user",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "string",
              name: "content",
              type: "string",
            },
          ],
          name: "TodoCreated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "user",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
          ],
          name: "TodoDeleted",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_id",
              type: "uint256",
            },
          ],
          name: "completeTodo",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "_content",
              type: "string",
            },
          ],
          name: "createTodo",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_id",
              type: "uint256",
            },
          ],
          name: "deleteTodo",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "getTodos",
          outputs: [
            {
              components: [
                {
                  internalType: "uint256",
                  name: "id",
                  type: "uint256",
                },
                {
                  internalType: "string",
                  name: "content",
                  type: "string",
                },
                {
                  internalType: "bool",
                  name: "isCompleted",
                  type: "bool",
                },
                {
                  internalType: "uint256",
                  name: "createdAt",
                  type: "uint256",
                },
                {
                  internalType: "address",
                  name: "user",
                  type: "address",
                },
              ],
              internalType: "struct TodoList.Todo[]",
              name: "",
              type: "tuple[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
    YourContract: {
      address: "0xA778159A811025756B5828b2F85cEaAC8b2a47F6",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "_owner",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "greetingSetter",
              type: "address",
            },
            {
              indexed: false,
              internalType: "string",
              name: "newGreeting",
              type: "string",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "premium",
              type: "bool",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
          ],
          name: "GreetingChange",
          type: "event",
        },
        {
          inputs: [],
          name: "greeting",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "premium",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "_newGreeting",
              type: "string",
            },
          ],
          name: "setGreeting",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [],
          name: "totalCounter",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "userGreetingCounter",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "withdraw",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          stateMutability: "payable",
          type: "receive",
        },
      ],
      inheritedFunctions: {},
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
